[project]
base_dir = "."           # base directory to operate in (for monorepos)
src_dir = "./src"        # source directory (under the base directory) from which context will be retrieved

[run]
build = "npm run build"
test = "npm run test"
lint = "quick-lint-js"

[gptengineer-app]
project_id = "b1fbdf99-3579-4cd7-90a0-7775aa96ebe0"
openapi = []
